---
name: "Trigger Downstream Build"
author: "Kenzi Stewart <kstewart@speareducation.com>"
description: "Triggers a downstream docker build by branching, updating configuration, and committing"
inputs:
  path:
    description: Path relative to GITHUB_WORKSPACE containing the repository to trigger
    required: true
  branch-prefix:
    description: Prefix to use when creating branch (e.g. "upstream/")
    required: false
    default: "upstream/"
  triggering-version:
    description: Upstream version (in semver format) to trigger in child build
    required: true
  change-type:
    description: in Semver parlance, which type of change this is (major/minor/patch)
    required: false
    default: patch
  github-pat:
    description: Personal access token with commit access to downstream git repository
    required: true
runs:
  using: "composite"
  steps:
    - name: Create upstream branch
      shell: bash
      run: |
        REPOSITORY_DIRNAME=$(echo "${{ inputs.repository }}" | sed -e 's%/%-%g')
        cd "${GITHUB_WORKSPACE}/${REPOSITORY_DIRNAME}" || { echo "Could not change to directory. Exiting." && exit 254; }
        UPSTREAM_BRANCH_PREFIX="${{ inputs.branch-prefix }}"
        TRIGGERING_VERSION="${{ inputs.triggering-version }}"
        git checkout -b "${UPSTREAM_BRANCH_PREFIX}/test-${TRIGGERING_VERSION}"
    - name: Update .config with new upstream version
      shell: bash
      run: |
        REPOSITORY_DIRNAME=$(echo "${{ inputs.repository }}" | sed -e 's%/%-%g')
        cd "${GITHUB_WORKSPACE}/${REPOSITORY_DIRNAME}" ||  { echo "Could not change to directory. Exiting." && exit 254; }
        TRIGGERING_VERSION="${{ inputs.triggering-version }}"
        sed -i -e "s/^DOCKER_BASE_IMAGE_VER=.*$/DOCKER_BASE_IMAGE_VER=${TRIGGERING_VERSION}/g" .config
    - name: Commit updated config to dependent repository
      shell: bash
      run: |
        REPOSITORY_DIRNAME=$(echo "${{ inputs.repository }}" | sed -e 's%/%-%g')
        cd "${GITHUB_WORKSPACE}/${REPOSITORY_DIRNAME}" || { echo "Could not change to directory. Exiting." && exit 254; }
        git add .config
        case "${{ inputs.change-type }}" in
          patch)
            CHANGE_TYPE=""
            ;;
          minor)
            CHANGE_TYPE="feat:"
            ;;
          major)
            CHANGE_TYPE="BREAKING CHANGE:"
            ;;
        esac
        git commit -m "${CHANGE_TYPE} updated base image to version ${TRIGGERING_VERSION}"
        UPSTREAM_BRANCH_PREFIX="${{ inputs.branch-prefix }}"
        TRIGGERING_VERSION="${{ inputs.triggering-version }}"
        git push origin "${UPSTREAM_BRANCH_PREFIX}/test-${TRIGGERING_VERSION}"
